name: CI Pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Pylint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run Pylint
        run: |
          pipenv run pylint .

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev

      - name: Run Pytest
        run: |
          pipenv run pytest
